name: Fetch instrument data

on:
  workflow_dispatch:

jobs:
  fetch-instruments:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Fetch data
        run: ./scripts/fetch-instruments.sh
      - name: Process data
        run: node -v
      - name: Commit changes
        run: |
          git config --global user.name 'cronie'
          git config --global user.email 'cronie@nope.com'
          git add .
          git commit -am "Automated data fetch"
          git push
